import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { ModelsDevRegistry } from '../../src/reasoning/registry/types-v2'

const ROOT = process.cwd()
const NL = String.fromCharCode(10)
const MDEV = JSON.parse(readFileSync(join(ROOT, 'src', 'generated', 'models-dev-registry.json'), 'utf8')) as ModelsDevRegistry
const RESOLUTIONS = JSON.parse(readFileSync(join(ROOT, 'registry', 'evidence', 'resolutions.json'), 'utf8')) as { resolutions: Array<{ model: string; kind: string; prefer: string }> }
const BASE = JSON.parse(readFileSync(join(ROOT, 'registry', 'evidence', 'base-models.json'), 'utf8')) as { relations: Array<{ model: string; baseModel: string; confidence: string }> }

const c = MDEV.coverage
const ids = MDEV.models
const byRes = new Map<string, number>()
for (const m of ids) byRes.set(m.identityResolution ?? 'unknown', (byRes.get(m.identityResolution ?? 'unknown') ?? 0) + 1)
const layers = {
  officialOnly: ids.filter((m) => m.layers.official && !m.layers.modelsDev).length,
  both: ids.filter((m) => m.layers.official && m.layers.modelsDev).length,
  modelsDevOnly: ids.filter((m) => m.layers.modelsDev && !m.layers.official).length,
  inferred: ids.filter((m) => m.layers.inferred).length,
}
const conflictKinds = new Map<string, number>()
for (const r of RESOLUTIONS.resolutions) conflictKinds.set(r.kind, (conflictKinds.get(r.kind) ?? 0) + 1)
const unresolvedIdentity = byRes.get('unresolved') ?? 0
const aliasesTotal = ids.reduce((n, m) => n + (m.aliases?.length ?? 0), 0)
const fam = ids.filter((m) => m.family)

const md: string[] = []
md.push('# G4 merge audit (models.dev evidence overlay)')
md.push('')
md.push('Generated by registry:audit. Compiled: ' + MDEV._notice.replace('GENERATED - ', ''))
md.push('')
md.push('| Artifact | Value |')
md.push('|---|---|')
md.push('| registryVersion (v2) | ' + MDEV.registryVersion + ' |')
md.push('| schemaVersion | ' + MDEV.schemaVersion + ' |')
md.push('| snapshot fetchedAt | ' + MDEV.source.fetchedAt + ' |')
md.push('| snapshot sha256 | ' + MDEV.source.snapshotSha256.slice(0, 16) + '... |')
md.push('| compiled records | ' + ids.length + ' |')
md.push('')
md.push('## Coverage accounting (G4 sections 5, 31)')
md.push('')
md.push('| Metric | Value |')
md.push('|---|---|')
md.push('| provider models scanned | ' + c.providerModelsScanned + ' |')
md.push('| provider-agnostic scanned | ' + c.providerAgnosticScanned + ' |')
md.push('| reasoning=true | ' + c.reasoningTrue + ' |')
md.push('| reasoning_options present | ' + c.reasoningOptionsPresent + ' |')
md.push('| controls known | ' + c.controlsKnown + ' |')
md.push('| controls unknown | ' + c.controlsUnknown + ' |')
md.push('| base-model linked (snapshot) | ' + c.baseModelFromSnapshot + ' |')
md.push('| base-model relations declared (evidence) | ' + c.baseModelRelationsDeclared + ' (applied ' + c.baseModelFromEvidence + ') |')
md.push('| conflicts during build | ' + c.conflictsDuringBuild + ' |')
md.push('| resolutions applied / required | ' + c.resolutionsApplied + ' / ' + c.resolutionsRequired + ' |')
md.push('| silently dropped | ' + c.silentlyDropped + ' |')
md.push('')
md.push('## Evidence layers')
md.push('')
md.push('| Layer | Records |')
md.push('|---|---|')
md.push('| official only | ' + layers.officialOnly + ' |')
md.push('| official + models.dev | ' + layers.both + ' |')
md.push('| models.dev only | ' + layers.modelsDevOnly + ' |')
md.push('| inferred | ' + layers.inferred + ' |')
md.push('')
// S2 resolution lifecycle (read from compiled artifact + declared list).
const appliedModels = new Set(ids.filter((m) => m.conflictResolution).map((m) => m.model))
const existingModels = new Set(ids.map((m) => m.model))
let activeR = 0
let staleR = 0
let invalidR = 0
for (const r of RESOLUTIONS.resolutions) {
  if (!existingModels.has(r.model)) invalidR++
  else if (appliedModels.has(r.model)) activeR++
  else staleR++
}
md.push('')
// E1 - official evidence age audit (maintenance warning only; never treated as stale by itself).
const officialEvidence: Array<{ verifiedAt?: string }> = []
for (const m of ids) for (const e of m.evidence) if (e.type === 'vendor-official-doc' || e.type === 'manual-verified') officialEvidence.push({ verifiedAt: e.verifiedAt })
const now = Date.now()
let evFresh = 0
let ev31to90 = 0
let evOld = 0
let evMissing = 0
for (const ev of officialEvidence) {
  if (!ev.verifiedAt || !/^\d{4}-\d{2}-\d{2}$/.test(ev.verifiedAt)) { evMissing++; continue }
  const days = Math.floor((now - Date.parse(ev.verifiedAt + 'T00:00:00Z')) / 86400000)
  if (days <= 30) evFresh++
  else if (days <= 90) ev31to90++
  else evOld++
}
md.push('')
md.push('## Official evidence maintenance (E1)')
md.push('')
md.push('| Age | Count |')
md.push('|---|---|')
md.push('| total official/manual evidence | ' + officialEvidence.length + ' |')
md.push('| verified <= 30 days | ' + evFresh + ' |')
md.push('| 31-90 days | ' + ev31to90 + ' |')
md.push('| > 90 days (maintenance warning) | ' + evOld + ' |')
md.push('| missing verifiedAt | ' + evMissing + ' |')
md.push('')
md.push('## Resolution lifecycle (S2)')
md.push('')
md.push('| Status | Count |')
md.push('|---|---|')
md.push('| active | ' + activeR + ' |')
md.push('| stale | ' + staleR + ' |')
md.push('| invalid | ' + invalidR + ' |')
md.push('')
md.push('## Conflict resolutions (explicit, no silent overwrite)')
md.push('')
for (const [kind, n] of conflictKinds) md.push('- ' + kind + ': ' + n + (kind === 'flag-conflict' ? ' (relay observation vs official capability)' : kind === 'md-extra' ? ' (models.dev extra effort values; official authoritative)' : kind === 'md-controls-only' ? ' (models.dev controls vs official none)' : ''))
md.push('')
md.push('Resolved models: ' + RESOLUTIONS.resolutions.map((r) => r.model).join(', '))
md.push('')
md.push('## Identity resolution (G4.4)')
md.push('')
md.push('| Identity | Records |')
md.push('|---|---|')
for (const [k, n] of byRes) md.push('| ' + k + ' | ' + n + ' |')
md.push('| relay alias bindings (unique) | ' + aliasesTotal + ' |')
md.push('')
md.push('## Base-model relations (G4.3)')
md.push('')
md.push('Declared: ' + BASE.relations.length + '. Snapshot supply: ' + c.baseModelFromSnapshot + '.')
if (BASE.relations.length === 0) {
  md.push('')
  md.push('> Data gap: models.dev 2026-08 api.json provides NO base_model field for any provider model. Base relations are recorded through the evidence layer only; pipeline ready to consume snapshot base_model when upstream publishes it.')
} else {
  for (const rl of BASE.relations) md.push('- ' + rl.model + ' -> ' + rl.baseModel + ' (confidence ' + rl.confidence + ')')
}
md.push('')
md.push('## Family aggregation (G4.5)')
md.push('')
if (fam.length === 0) {
  md.push('No family assignments (no identity evidence).')
} else {
  for (const m of fam) md.push('- ' + m.model + ' in family ' + m.family)
}
md.push('')
// S1 minimal effort semantics audit.
let minimalModels = 0
let minimalOfficialConfirmed = 0
let minimalModelsDevOnly = 0
let minimalNormalized = 0
let minimalEffectiveIndependent = 0
let minimalConflict = 0
for (const m of ids) {
  let hasMinimalAccepted = false
  let hasMinimalEffective = false
  for (const c of m.reasoning.controls ?? []) {
    if (c.type !== 'effort') continue
    if ((c.acceptedValues ?? []).includes('minimal')) hasMinimalAccepted = true
    if ((c.effectiveValues ?? []).includes('minimal')) hasMinimalEffective = true
  }
  if (!hasMinimalAccepted) continue
  minimalModels++
  if (m.layers.official) minimalOfficialConfirmed++
  else minimalModelsDevOnly++
  if (hasMinimalEffective) minimalEffectiveIndependent++
  if (m.conflictResolution) minimalConflict++
  // normalization that maps minimal elsewhere (currently none without evidence)
  for (const c of m.reasoning.controls ?? []) {
    if (c.type === 'effort' && c.normalization && c.normalization['minimal']) minimalNormalized++
  }
}

md.push('')
md.push('## S1 reasoning semantics (accepted vs effective)')
md.push('')
md.push('| Metric | Value |')
md.push('|---|---|')
md.push('| minimal records | ' + minimalModels + ' |')
md.push('| official semantic confirmed | ' + minimalOfficialConfirmed + ' |')
md.push('| models.dev only (semantic unknown) | ' + minimalModelsDevOnly + ' |')
md.push('| normalized to another level | ' + minimalNormalized + ' |')
md.push('| independent effective level | ' + minimalEffectiveIndependent + ' |')
md.push('| conflicts | ' + minimalConflict + ' |')
md.push('')
md.push('## Data gaps & notes')
md.push('')
md.push('- models.dev base_model absent in the 2026-08 snapshot (see above).')
md.push('- Unsupported reasoning option types collected by sync fail closed (G4 section 21); current snapshot has none.')
md.push('- Relay observations may disagree with official curated capability; all disagreements are explicit resolutions with prefer: official-exact.')
md.push('- unresolved identity keys (' + unresolvedIdentity + ') have no known vendor anchor in the 8 curated vendors; kept on their own key and accounted - never guessed.')

const out = md.join(NL) + NL
mkdirSync(join(ROOT, 'docs'), { recursive: true })
const f = join(ROOT, 'docs', 'g4-merge-audit.md')
writeFileSync(f, out)
console.log('wrote ' + f)
console.log('reasoning=true=' + c.reasoningTrue + ' controls-known=' + c.controlsKnown + ' unresolved-identity=' + unresolvedIdentity + ' conflicts=' + c.conflictsDuringBuild + ' resolutions=' + c.resolutionsRequired)
